config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :complaints, except: [:create]
  resources :conpanies do
      resources :complaints, only: [:create]
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'conpanies#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user
  belongs_to :conpany
end

app/models/conpany.rb
class Conpany < ApplicationRecord
    has_many :complaints, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :complaints, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:index]
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  

def create
  @complaint = Complaint.new(complaint_params)
  @complaint.user = current_user
  @complaint.conpany_id = params[:conpany_id]
  respond_to do |format|
    if @complaint.save
      format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
      format.json { render :show, status: :created, location: @complaint }
      format.js {}
    else
      format.html { render :new }
      format.json { render json: @complaint.errors, status: :unprocessable_entity }
    end
 end
end



  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:user_id, :conpany_id, :content)
    end
end

app/controllers/conpanies_controller.rb
class ConpaniesController < ApplicationController
  before_action :set_conpany, only: [:show, :edit, :update, :destroy]
  

  # GET /conpanies
  # GET /conpanies.json
  def index
    @conpanies = Conpany.all
    @conpany = Conpany.new
  end

  # GET /conpanies/1
  # GET /conpanies/1.json
  def show
    @complaint = Complaint.new
  end

  # GET /conpanies/new
  def new
    @conpany = Conpany.new
  end

  # GET /conpanies/1/edit
  def edit
  end

  # POST /conpanies
  # POST /conpanies.json
  def create
    @conpany = Conpany.new(conpany_params)

    respond_to do |format|
      if @conpany.save
        format.html { redirect_to @conpany, notice: 'Conpany was successfully created.' }
        format.json { render :show, status: :created, location: @conpany }
        format.js 
      else
        format.html { render :new }
        format.json { render json: @conpany.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conpanies/1
  # PATCH/PUT /conpanies/1.json
  def update
    respond_to do |format|
      if @conpany.update(conpany_params)
        format.html { redirect_to conpanies_path , notice: 'Conpany was successfully updated.' }
        format.json { render :show, status: :ok, location: @conpany }
        
      else
        format.html { render :edit }
        format.json { render json: @conpany.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conpanies/1
  # DELETE /conpanies/1.json
  def destroy
    @conpany.destroy
    respond_to do |format|
      format.html { redirect_to conpanies_url, notice: 'Conpany was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conpany
      @conpany = Conpany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conpany_params
      params.require(:conpany).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/conpanies_helper.rb
module ConpaniesHelper
end

app/views/complaints/_complaint.js.erb
<tr>
<td><%= complaint.user_id %></td>
<td><%= complaint.content %></td>
</tr>

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, url: conpany_complaints_url(conpany.id)) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul >
        <% complaint.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :reclamo %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complaints/create.js.erb
$('#show_').prepend('<li> <%= @complaint.content %> <%= @complaint.user.email %> </li>');

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Conpany</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.user_id %></td>
        <td><%= complaint.conpany_id %></td>
        <td><%= complaint.content %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @complaint.user_id %>
</p>

<p>
  <strong>Conpany:</strong>
  <%= @complaint.conpany_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @complaint.content %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>

app/views/conpanies/_conpany.html.erb
<tr id="conpany_<%= conpany.id%>">
        <td><%= conpany.name %></td>
        <td><%= link_to 'Show', conpany %></td>
        <td><%= link_to 'Edit', edit_conpany_path(conpany), data: {remote: true} %></td>
        <td><%= link_to 'Destroy', conpany, method: :delete, data: { confirm: 'Are you sure?' , remote: true } %></td>
      </tr>

app/views/conpanies/_form.html.erb
<%= form_with(model: conpany) do |form| %>
  <% if conpany.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conpany.errors.count, "error") %> prohibited this conpany from being saved:</h2>

      <ul>
        <% conpany.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conpanies/create.js.erb
$('table > tbody:last-child').append('<%= j render @conpany%>');

app/views/conpanies/destroy.js.erb
$('#conpany_<%= @conpany.id%>').toggle();

app/views/conpanies/edit.html.erb
<h1>Editing Conpany</h1>

<%= render 'form', conpany: @conpany %>

<%= link_to 'Show', @conpany %> |
<%= link_to 'Back', conpanies_path %>

app/views/conpanies/edit.js.erb
$('.modal-body').html("<%= j render 'form', conpany: @conpany%>")
$('#myModal').modal('show');

app/views/conpanies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conpanies</h1>
<%= render 'form', conpany: @conpany%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @conpanies%>
  </tbody>
  <hr>
</table>

<br>
<div class="modal" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body ">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<%= link_to 'New Conpany', new_conpany_path %>

app/views/conpanies/new.html.erb
<h1>New Conpany</h1>

<%= render 'form', conpany: @conpany %>

<%= link_to 'Back', conpanies_path %>

app/views/conpanies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conpany.name %>
</p>
<%= render 'complaints/form', complaint: @complaint, conpany: @conpany %>
<ul id="show_">

  <% @conpany.complaints.order(created_at: :desc).each do |complaint| %>
<li>
 
  
<%= complaint.content %>

<%= complaint.user.email %></li>
<% end %>
</ul>



<%= link_to 'Edit', edit_conpany_path(@conpany) %> |
<%= link_to 'Back', conpanies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxsTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
  <%=render 'shared/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light text-light bg-info">
    <a class="navbar-brand">
      <h5>Ajax</h5>
    </a>
    <ul class="nav item">
        
      <% if user_signed_in? %>
      
      
        <li class="nav-item <%= 'active' if action_name == 'Salir'%>">
        
        <%= link_to "Salir", destroy_user_session_path, method: :delete, class:"nav-item nav-link text-dark" %>
        </li>
        <%else%>
        <li>
        
        <%= link_to "Inicio", new_user_session_path,class:"nav-item nav-link text-dark" %>
        </li>
        <li>
        
        <%= link_to "Registrar", new_user_registration_path, class:"nav-item nav-link text-dark" %>
        </li>
        
        <% end %>
        </li>
      </ul>
  </nav>